### ISSUE TITLE
Visualize progress graphically in a way related to solving a algorithm

### ISSUE THREAD

**Issue by danielbh** [Minierre/fortysix#121]
- [x] JSON treeview

**Comment by abelmcelroy** [comment]
suggestion: the best information we have as a the admin is the generational depth of the population. we should make the visualization relate to that. its a form of progress bar in a real sense and it relies on very little computation on the part of the admin

**Comment by danielbh** [comment]
Ideas: https://codepen.io/jareilly/pen/NGaLap

**Comment by danielbh** [comment]
https://konvajs.github.io
