### ISSUE TITLE
Room issues

### ISSUE THREAD

**Issue by danielbh** [Minierre/fortysix#249]
- [x] When a user presses the back button in a room they leave the room - emit leave on componentWillUnmount
- [x] If there are no people in the room reset the room with a new instance.
- [x] room doesn't update UI when the job ends

**Comment by Schwartz10** [comment]
1. Join game of life room as admin
2. join game of life room as contributor
3. begin running job
4. contributor clicks back (and leaves the room)
5. contributor re-enters the room

app crashes - finishedTask needs to include fitnesses! 

(LOL - we hit the random error check)

this happens because for some reason, when a client reconnects after clicking back, it sends back an empty task item without fitness

**Comment by Schwartz10** [comment]
1. server throws an error, stopping the server
2. client and admin refresh
3. no job init function was run (so new roomStats() is not instantiated)
4. client sends back an empty task object (not sure why)
5. this.generateStats is not a function

why does the client send back an empty task object on rejoining?

**Comment by Schwartz10** [comment]
On the bright side, rooms are actually isolated from contributors in other rooms!

**Comment by Schwartz10** [comment]
Upon further review of the back button issue, it seems it's a bit more complicated than putting a `componentDidUnmount` which socket.emits the leave call - in fact, this code was already on the page. 

The back button does not trigger react lifecycle components. There are a couple of solutions which I weaseled around with, but couldn't figure out the simplest/cleanest approach. One way is to use the window.onpopstate event which fires on a back button click. However, the following approach seems the most promising - 

class Foo extends Component {
  componentDidMount() {
    this.props.router.setRouteLeaveHook(this.props.route, this.routerWillLeave);
  }

  routerWillLeave(nextState) { // return false to block navigation, true to allow
    if (nextState.action === 'POP') {
      // handle "Back" button clicks here
    }
  }
}

But looking for additional suggestions on the back button issue. It also causes another issue upon re-entering the room, which i listed above
